### ISSUE TITLE
Add review policy

### ISSUE THREAD

**Issue by janine9vn** [python-discord/sir-robin#2]
I'd like to add a review policy to Sir Robin, to ensure good, robust features.

I'd like the review policy to be:
- 1 Core Dev/Events Lead
- 1 Contrib

I'd like to trial this review policy for awhile. If we find it's too restrictive, then we can adjust it to also accept Events Team review in lieu of Core Dev.

**Comment by ChrisLovering** [comment]
Resolved with https://github.com/python-discord/sir-robin/commit/48ea8cbcabfa493c66f9e9f342eeb666499342bb
