### ISSUE TITLE
Add `&cj pin` command for participants to use

### ISSUE THREAD

**Issue by janine9vn** [python-discord/sir-robin#53]
Participants in our code jam have asked for a way to pin things in their channel. We can't reasonably give them the native Discord permission, but we do have bots. Let's use the bots.

This command should be usable by Admins, Events Team, and anyone with the Code Jam Participants Role. It'll let people pin/un-pin messages **only** in their team channel via the bot. This should work with a reply to a message and also a message link.

I figure one way to do this is have a wonky role-check-like-object to see if their role matches the channel name? If it does, allow it? Maybe?

**Comment by D0rs4n** [comment]
We can use the Code Jam MGMT API, and do a basic ID check. I can do this.

**Comment by DMFriends** [comment]
I really like this idea. (Note: I'm not a participant). How would the command work? Like reply to a message and invoke the command, similar to the `.uwu` command on Lancebot? I think that's probably the best way to implement this. Just stating my opinion.

**Comment by D0rs4n** [comment]
> 

Yes, exactly like this. We need to add a "middleware" though, to check the channel ID, but basically what you said.
